name: Build and Release

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        override: true

    - name: Add x86_64-unknown-none target
      run: rustup target add x86_64-unknown-none

    - name: Install cbindgen
      run: cargo install cbindgen

    - name: Add rust-src component
      run: rustup component add rust-src

    - name: Build general release
      run: |
        cargo build --release
        mv target/x86_64-unknown-none/release/libmath.a libmath-x86_64.a
        mv target/i686-unknown-none/release/libmath.a libmath-i686.a

    - name: Generate header
      run: cbindgen --output math.h

    - name: Release artifacts
      uses: softprops/action-gh-release@v2
      with:
        name: Nightly build
        tag_name: release
        files: |
          libmath-i686.a
          libmath-x86_64.a
          math.h
